

spring.datasource.url=jdbc:postgresql://dpg-d70d182a214c73e7pub0-a:5432/portfolio_db_9hdn
spring.datasource.username=portfolio_db_9hdn_user
spring.datasource.password=C93ycYtZf17qD4mlfMQBPBiCx9r2t8l8


app.cors.allowed-origins=https://portfolio-admin-wheat-gamma.vercel.app,https://portfolio-react-tailwind-nu.vercel.app